### ISSUE TITLE
Add xfab to conda-forge anaconda channel 

### ISSUE THREAD

**Issue by AxelHenningsson** [FABLE-3DXRD/xfab#26]
Make xfab anaconda installable as .

`conda install -c conda-forge xfab`

By adding xfab to the [conda-forge staged recepies](https://github.com/conda-forge/staged-recipes). This will require creating a LICENSE file in the root of the repo. Furthermore, this requires generating a recipe, preferably using [`grayskull`](https://pypi.org/project/grayskull/). First tries looks something like this:

```yaml
{% set name = "xfab" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xfab-{{ version }}.tar.gz
  sha256: 1fd85f91bb04701d82068d6ffcda2c4f38ea3f6b9a2d915f35e1fb95fe9a7cfd

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - pycifrw
    - python
    - six

test:
  imports:
    - xfab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FABLE-3DXRD/xfab
  summary: Crystallographic toolbox and library
  license: GPL-2.0-or-later
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - AxelHenningsson
```
